<?php
 $imphtml.= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">";
 $imphtml.= "<!--";
 $imphtml.= "Design by Free CSS Templates";
 $imphtml.= "http://www.freecsstemplates.org";
 $imphtml.= "Released for free under a Creative Commons Attribution 2.5 License";

 $imphtml.= "Name       : Impeccable   ";
 $imphtml.= "Description: A two-column, fixed-width design with dark color scheme.";
 $imphtml.= "Version    : 1.0";
 $imphtml.= "Released   : 20101129";

 $imphtml.= "-->";
 $imphtml.= "<html xmlns=\"http://www.w3.org/1999/xhtml\">";
 $imphtml.= "<head>";

 $imphtml.= "<meta name=\"keywords\" content=\"\" />";
 $imphtml.= "<meta name=\"description\" content=\"\" />";
 $imphtml.= "<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />";
 $imphtml.= "<title>Impeccable    by Free CSS Templates</title>";
 $imphtml.= "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />";
 $imphtml.= "</head>";
 $imphtml.= "<body>";
 $imphtml.= "<div id=\"wrapper\">";
 $imphtml.= "<div id=\"page\">";
 $imphtml.= "	<div id=\"page-bgtop\">";
 $imphtml.= "		<div id=\"page-bgbtm\">";
 $imphtml.= "			<div id=\"content\">";
 $imphtml.= "				<div class=\"post\">";
 $imphtml.= "					<h2 class=\"title\"><a href=\"#\">Welcome to Impeccable </a></h2>";
 $imphtml.= "					<p class=\"meta\"><span class=\"date\">November 10, 2010</span><span class=\"posted\">Posted by <a href=\"#\">Someone</a></span></p>";
 $imphtml.= "					<div style=\"clear: both;\">&nbsp;</div>";
 $imphtml.= "					<div class=\"entry\">";
 $imphtml.= "						<p>This is <strong>Impeccable </strong>, a free, fully standards-compliant CSS template designed by FreeCssTemplates<a href=\"http://www.nodethirtythree.com/\"></a> for <a href=\"http://www.freecsstemplates.org/\">Free CSS Templates</a>.  This free template is released under a <a href=\"http://creativecommons.org/licenses/by/2.5/\">Creative Commons Attributions 2.5</a> license, so you’re pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :)</p>";
 $imphtml.= "						<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. Donec ut ante. In id eros. Suspendisse turpis, egestas at sem.</p>";
 $imphtml.= "						<p class=\"links\"><a href=\"#\">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">Comments</a></p>";
 $imphtml.= "					</div>";
 $imphtml.= "				</div>";
 $imphtml.= "				<div class=\"post\">";
 $imphtml.= "					<h2 class=\"title\"><a href=\"#\">Lorem ipsum sed aliquam</a></h2>";
 $imphtml.= "					<p class=\"meta\"><span class=\"date\">November 10, 2010</span><span class=\"posted\">Posted by <a href=\"#\">Someone</a></span></p>";
 $imphtml.= "					<div style=\"clear: both;\">&nbsp;</div>";
 $imphtml.= "					<div class=\"entry\">";
 $imphtml.= "						<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href=\"#\">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem.  Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.</p>";
 $imphtml.= "						<p class=\"links\"><a href=\"#\">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">Comments</a></p>";
 $imphtml.= "					</div>";
 $imphtml.= "				</div>";
 $imphtml.= "				<div class=\"post\">";
 $imphtml.= "					<h2 class=\"title\"><a href=\"#\">Consecteteur hendrerit </a></h2>";
 $imphtml.= "		 			<p class=\"meta\"><span class=\"date\">November 10, 2010</span><span class=\"posted\">Posted by <a href=\"#\">Someone</a></span></p>";
 $imphtml.= "					<div style=\"clear: both;\">&nbsp;</div>";
 $imphtml.= "					<div class=\"entry\">";
 $imphtml.= "						<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href=\"#\">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem.  Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.</p>";
 $imphtml.= "						<p class=\"links\"><a href=\"#\">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">Comments</a></p>";
 $imphtml.= "					</div>";
 $imphtml.= "				</div>";
 $imphtml.= "				<div class=\"post\">";
 $imphtml.= "					<h2 class=\"title\"><a href=\"#\">Suspendisse hendrerit </a></h2>";
 $imphtml.= "					<p class=\"meta\"><span class=\"date\">November 10, 2010</span><span class=\"posted\">Posted by <a href=\"#\">Someone</a></span></p>";
 $imphtml.= "					<div style=\"clear: both;\">&nbsp;</div>";
 $imphtml.= "					<div class=\"entry\">";
 $imphtml.= "						<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href=\"#\">dapibus semper urna</a>. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem.  Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.</p>";
 $imphtml.= "						<p class=\"links\"><a href=\"#\">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">Comments</a></p>";
 $imphtml.= "					</div>";
 $imphtml.= "				</div>";
 $imphtml.= "				<div style=\"clear: both;\">&nbsp;</div>";
 $imphtml.= "			</div>";
 $imphtml.= "			<!-- end #content -->";
 $imphtml.= "			<div class=\"content\" id=\"sidebar\">";
 $imphtml.= "				<div id=\"logo\">";
 $imphtml.= "					<h1><a href=\"#\">Impeccable </a></h1>";
 $imphtml.= "					<p>Design by <a href=\"http://www.freecsstemplates.org/\">CSS Templates</a></p>";
 $imphtml.= "				</div>";

//******
 $imphtml.= "				<div class=\"post\">";
 $imphtml.= "					<h2 class=\"title\"><a href=\"#\">Welcome to Impeccable </a></h2>";
 $imphtml.= "					<p class=\"meta\"><span class=\"date\">November 10, 2010</span><span class=\"posted\">Posted by <a href=\"#\">Someone</a></span></p>";
 $imphtml.= "					<div style=\"clear: both;\">&nbsp;</div>";
 $imphtml.= "					<div class=\"entry\">";
 $imphtml.= "						<p>This is <strong>Impeccable </strong>, a free, fully standards-compliant CSS template designed by FreeCssTemplates<a href=\"http://www.nodethirtythree.com/\"></a> for <a href=\"http://www.freecsstemplates.org/\">Free CSS Templates</a>.  This free template is released under a <a href=\"http://creativecommons.org/licenses/by/2.5/\">Creative Commons Attributions 2.5</a> license, so you’re pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :)</p>";
 $imphtml.= "						<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. Donec ut ante. In id eros. Suspendisse turpis, egestas at sem.</p>";
 $imphtml.= "						<p class=\"links\"><a href=\"#\">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">Comments</a></p>";
 $imphtml.= "					</div>";
 $imphtml.= "				</div>";
 
//*****


 $imphtml.= "				<div id=\"menu\">";
 $imphtml.= "					<ul>";
 $imphtml.= "						<li class=\"current_page_item\"><a href=\"#\">Home</a></li>";
 $imphtml.= "						<li><a href=\"#\">Blog</a></li>";
 $imphtml.= "						<li><a href=\"#\">Photos</a></li>";
 $imphtml.= "						<li><a href=\"#\">About</a></li>";
 $imphtml.= "						<li><a href=\"#\">Links</a></li>";
 $imphtml.= "						<li><a href=\"#\">Contact</a></li>";
 $imphtml.= "					</ul>";
 $imphtml.= "				</div>";
 $imphtml.= "				<ul>";
 $imphtml.= "					<li>";
 $imphtml.= "						<div id=\"search\" >";
 $imphtml.= "							<form method=\"get\" action=\"#\">";
 $imphtml.= "								<div>";
 $imphtml.= "									<input type=\"text\" name=\"s\" id=\"search-text\" value=\"\" />";
 $imphtml.= "									<input type=\"submit\" id=\"search-submit\" value=\"GO\" />";
 $imphtml.= "								</div>";
 $imphtml.= "							</form>";
 $imphtml.= "						</div>";
 $imphtml.= "						<div style=\"clear: both;\">&nbsp;</div>";
 $imphtml.= "					</li>";
 $imphtml.= "					<li>";
 $imphtml.= "						<h2>Aliquam tempus</h2>";
 $imphtml.= "						<p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper consectetuer hendrerit.</p>";
 $imphtml.= "					</li>";
 $imphtml.= "					<li>";
 $imphtml.= "						<h2>Categories</h2>";
 $imphtml.= "						<ul>";
 $imphtml.= "							<li><a href=\"#\">Aliquam libero</a></li>";
 $imphtml.= "							<li><a href=\"#\">Consectetuer adipiscing elit</a></li>";
 $imphtml.= "							<li><a href=\"#\">Metus aliquam pellentesque</a></li>";
 $imphtml.= "							<li><a href=\"#\">Suspendisse iaculis mauris</a></li>";
 $imphtml.= "							<li><a href=\"#\">Urnanet non molestie semper</a></li>";
 $imphtml.= "							<li><a href=\"#\">Proin gravida orci porttitor</a></li>";
 $imphtml.= "						</ul>";
 $imphtml.= "					</li>";
 $imphtml.= "					<li>";
 $imphtml.= "						<h2>Blogroll</h2>";
 $imphtml.= "						<ul>";
 $imphtml.= "							<li><a href=\"#\">Aliquam libero</a></li>";
 $imphtml.= "							<li><a href=\"#\">Consectetuer adipiscing elit</a></li>";
 $imphtml.= "							<li><a href=\"#\">Metus aliquam pellentesque</a></li>";
 $imphtml.= "							<li><a href=\"#\">Suspendisse iaculis mauris</a></li>";
 $imphtml.= "							<li><a href=\"#\">Urnanet non molestie semper</a></li>";
 $imphtml.= "							<li><a href=\"#\">Proin gravida orci porttitor</a></li>";
 $imphtml.= "						</ul>";
 $imphtml.= "					</li>";
 $imphtml.= "					<li>";
 $imphtml.= "						<h2>Archives</h2>";
 $imphtml.= "						<ul>";
 $imphtml.= "							<li><a href=\"#\">Aliquam libero</a></li>";
 $imphtml.= "							<li><a href=\"#\">Consectetuer adipiscing elit</a></li>";
 $imphtml.= "							<li><a href=\"#\">Metus aliquam pellentesque</a></li>";
 $imphtml.= "							<li><a href=\"#\">Suspendisse iaculis mauris</a></li>";
 $imphtml.= "							<li><a href=\"#\">Urnanet non molestie semper</a></li>";
 $imphtml.= "							<li><a href=\"#\">Proin gravida orci porttitor</a></li>";
 $imphtml.= "						</ul>";
 $imphtml.= "					</li>";
 $imphtml.= "				</ul>";
 $imphtml.= "			</div>";
 $imphtml.= "			<!-- end #sidebar -->";
 $imphtml.= "			";
 $imphtml.= "			<div id=\"footer\">";
 $imphtml.= "				<p>Copyright (c) 2010 Sitename.com. All rights reserved. Design by <a href=\"http://www.freecsstemplates.org/\"> CSS Templates</a>.</p>";
 $imphtml.= "			</div>";
 $imphtml.= "		</div>";
 $imphtml.= "	</div>";
 $imphtml.= "	<!-- end #page -->";
 $imphtml.= "</div>";
 $imphtml.= "<!-- end #footer -->";
 $imphtml.= "</body>";
 $imphtml.= "</html>";
echo $imphtml;
?>